### ISSUE TITLE
Provide cats-effect 3 builds

### ISSUE THREAD

**Issue by arixmkii** [davenverse/epimetheus#182]
`cats-effect` 3.0 has reached RC state. Would be nice to provide -M or -RC build for this version. As it will contain breaking changes, I believe there will be a need to bump major version as well and adjust CI to build and publish from multiple branches.

I created a version, which builds against CE3 with this commit https://github.com/arixmkii/epimetheus/commit/ae04eafc40f7b47320d71799b72b547de98ac44e but it doesn't address CI and versioning in any way.

It also addresses #152 without losing ability to use different units for both `Summary` and `Histogram`.

I can provide changes as PR, when there will be separate branches for ce2 and ce3 (up to you, which one should be main for now), because obviously ce2 will be here to stay for some time.

**Comment by arixmkii** [comment]
#152 fix was tested with this example application

```scala

import cats.effect.{ExitCode, IO, IOApp}
import io.chrisdavenport.epimetheus.{CollectorRegistry, Histogram, Name}

import scala.concurrent.duration._

object SummaryApp extends IOApp {

  override def run(args: List[String]): IO[ExitCode] =
    for {
      r <- CollectorRegistry.build[IO]
      hist <- Histogram.noLabels(r, Name("hist"), "help")
      _ <- Histogram.timedSeconds(hist, IO.sleep(4.3.seconds))
      _ <- r.write004.map(println)
    } yield ExitCode.Success

}
```

And it outputs
```
# HELP hist help
# TYPE hist histogram
hist_bucket{le="0.005",} 0.0
hist_bucket{le="0.01",} 0.0
hist_bucket{le="0.025",} 0.0
hist_bucket{le="0.05",} 0.0
hist_bucket{le="0.075",} 0.0
hist_bucket{le="0.1",} 0.0
hist_bucket{le="0.25",} 0.0
hist_bucket{le="0.5",} 0.0
hist_bucket{le="0.75",} 0.0
hist_bucket{le="1.0",} 0.0
hist_bucket{le="2.5",} 0.0
hist_bucket{le="5.0",} 1.0
hist_bucket{le="7.5",} 1.0
hist_bucket{le="10.0",} 1.0
hist_bucket{le="+Inf",} 1.0
hist_count 1.0
hist_sum 4.314058097
# HELP hist_created help
# TYPE hist_created gauge
hist_created 1.613407055451E9
```

In comparison, for the current release hist_sum is 4.0 for the same app.

**Comment by arixmkii** [comment]
Mentioning this here to make it more traceable as part of global progress towards ce3 https://github.com/typelevel/cats-effect/issues/1330

**Comment by Kazark** [comment]
@ChristopherDavenport 🙏 `kafka4s` needs you
